### ISSUE TITLE
Error: lexical error: invalid char in json text.

### ISSUE THREAD

**Issue by naturofix** [genometra/SNPediaR#1]
I recently got these error while trying to use this package in RStudio on both MacOS and Ubuntu 16.04

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          4.2                         
year           2017                        
month          09                          
day            28                          
svn rev        73368                       
language       R                           
version.string R version 3.4.2 (2017-09-28)
nickname       Short Summer                

> biocLite("SNPediaR")
BioC_mirror: https://bioconductor.org
Using Bioconductor 3.5 (BiocInstaller 1.26.1), R 3.4.2 (2017-09-28).
Installing package(s) ‘SNPediaR’

> library(SNPediaR)

> pg <- getPages (titles = "rs1800255")
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^
> res <- getCategoryElements (category = "Is_a_medical_condition")
Error: lexical error: invalid char in json text.
                                       <!DOCTYPE HTML PUBLIC "-//IETF/
                     (right here) ------^

I will try to upgrade Bioconductor, to see if this helps

**Comment by dmontaner** [comment]
It seems that SNPedia web services have recently changed from HTTP to HTTPS. The issue should be solved now. Thank yo for reporting.
