### ISSUE TITLE
certificate problem abour SNPediaR

### ISSUE THREAD

**Issue by tmluanbu** [genometra/SNPediaR#4]
Error in function (type, msg, asError = TRUE) : SSL certificate problem: certificate is not yet valid.
It appears when I run the example code.
library (SNPediaR)
pg <- getPages (titles = "Rs53576")
pg
Anyone knows what happened?

**Comment by dmontaner** [comment]
The code works for me. The error seems something related with your curl set up or with Rstudio proxy setup. 
See here: 

- <https://support.rstudio.com/hc/en-us/community/posts/115000720967-Error-in-function-type-msg-asError-TRUE->
- <https://support.rstudio.com/hc/en-us/articles/200488488-Configuring-R-to-Use-an-HTTP-or-HTTPS-Proxy>
