### ISSUE TITLE
Unknown SSL protocol error in connection to bots.snpedia.com:443

### ISSUE THREAD

**Issue by amirinSofi** [genometra/SNPediaR#5]
Hi, 
I was trying to follow the tutorial for SNPediaR. 

`library (SNPediaR)`
`pg <- getPages (titles = "Rs53576") `
`pg`

But I got an error like this,
`Error in function (type, msg, asError = TRUE)  : `
 ` Unknown SSL protocol error in connection to bots.snpedia.com:443`

Can you help me to solve this problem?

Thanks in advance.

**Comment by hafizmtalha** [comment]
> Hi,
> I was trying to follow the tutorial for SNPediaR.
> 
> `library (SNPediaR)`
> `pg <- getPages (titles = "Rs53576") `
> `pg`
> 
> But I got an error like this,
> `Error in function (type, msg, asError = TRUE) : `
> ` Unknown SSL protocol error in connection to bots.snpedia.com:443`
> 
> Can you help me to solve this problem?
> 
> Thanks in advance.

did you find any help on this ?

**Comment by dmontaner** [comment]
Should be solved now.
